
export interface MasterData {
  id: string;
  skpd: string;
  kode_skpd: string;
  program: string;
  kode_program: string;
  kegiatan: string;
  kode_kegiatan: string;
  sub_kegiatan: string;
  kode_sub_kegiatan: string;
  belanja: string;
  kode_belanja: string;
  anggaran: number;
  realisasi: number;
  pagu_spd: number;
}

export interface RealizationData {
  id: string;
  skpd: string;
  kode_skpd: string;
  program: string;
  kode_program: string;
  kegiatan: string;
  kode_kegiatan: string;
  sub_kegiatan: string;
  kode_sub_kegiatan: string;
  belanja: string;
  kode_belanja: string;
  realisasi: number;
  keterangan_dokumen: string;
  tanggal?: string;
}

export interface ExpenditureData {
  id: string;
  kode_belanja: string;
  belanja: string;
}

export interface FinancialSummary {
  totalAnggaran: number;
  totalRealisasi: number;
  sisaAnggaran: number;
  persentase: number;
}

export interface HibahData {
  id: string;
  kegiatan: string;
  kode_kegiatan: string;
  sub_kegiatan: string;
  kode_sub_kegiatan: string;
  kode_rekening?: string;
  uraian?: string;
  penerima_hibah?: string;
  anggaran: number;
  spd: number;
  realisasi: number;
  sisa_spd: number;
  sisa_realisasi: number;
  isAutoGenerated?: boolean;
  sourceType?: 'auto_apbd' | 'auto_sp2d' | 'manual';
  createdAt?: any;
}

export type Page = 'dashboard' | 'master' | 'realization' | 'reports' | 'spreadsheet';
